### ISSUE TITLE
Add description to form introduction

### ISSUE THREAD

**Issue by luke-karis** [SuffolkLITLab/docassemble-PetitionToChangeNameOfAdult#1]

**Comment by anna-stone** [comment]
[Possible Description]

If you are an adult living in Massachusetts who wants to change your legal name, this form is for you.

In Massachusetts, an adult can request a legal name change by submitting a form, called the Petition to Change Name of Adult, to the court. The next few pages will ask you questions to gather the information needed for the form, and then the system will fill out the form for you. 

The questions will take about 15 minutes to answer. Once you're finished, you'll need to gather some documents, and then you can email your form and the documents to the court using this secure website.
