### ISSUE TITLE
Add an automated test

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-PetitionToChangeNameOfAdult#38]
Use the [Kiln](https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing) framework to add at least one automated test to this repository

**Comment by jacksondowd** [comment]
[variables.json](https://github.com/SuffolkLITLab/docassemble-PetitionToChangeNameOfAdult/files/14285586/variables.json)
